### ISSUE TITLE
한판 끝내고 다시 게임하기 후 플레이어가 레디하면 '이미 시작된 게임입니다'라고 나오는 문제

### ISSUE THREAD

**Issue by poqop721** [Team-def/recre-frontend#117]
플레이어 소켓이 null (랜덤) → isEmmitted 같은거로 막자
 ⇒ 소켓 연결은 한번인데 ready 요청이 여러번 들어옴

**Comment by ChoiWheatley** [comment]
unique/uuid  constraint failed → 한명이 두명으로 들어와짐

**Comment by poqop721** [comment]
소켓 여러번 보내지는거 해결하고 나니 같이 해결됨
