### ISSUE TITLE
Host/player 시간 다르게 나오는거

### ISSUE THREAD

**Issue by poqop721** [Team-def/recre-frontend#133]

**Comment by ChoiWheatley** [comment]
시작시간을 서버가 기준을 잡아줄까? 서버에 출발시간 & 끝나는 시간 둘 다 저장해도 된다.

**Comment by Designated-Hitter** [comment]
핸드폰 브라우저 내에서 new Date() 에 잡히는 시간과, host 컴퓨터에서 new Date()에 잡히는 시간이 다르기 때문에 이런 버그가 나올 수도 있는 것 같음. 솔직히 logic상에선 왜 문제가 발생하는 지 알 수 없음

**Comment by Designated-Hitter** [comment]
startTime을 player page에서 socket.current.on("start_game")에서 받아온 후, socket.current.on("ready")에서 setGameContent안의 변수로 start_time안에 넣어서 게임을 시작하게 하는 로직을 작성함
