### ISSUE TITLE
[FE] 게임이 끝나도 alive인 플레이어들이 모달창 안 뜨는 버그

### ISSUE THREAD

**Issue by ChoiWheatley** [Team-def/recre-frontend#147]

**Comment by Designated-Hitter** [comment]
bug: 무궁화 게임이 종료되었을 때 DEAD, FINISH 상태인 플레이어의 모바일 페이지에는 게임 결과 모달창이 정상적으로 뜨나, ALIVE 상태에서 게임이 끝난 플레이어의 모바일 페이지에는 모달창이 뜨지 않는다.
