### ISSUE TITLE
캐치마인드에서 플레이어의 오답 입력이 많아지면 마우스 그림이 끊기는 문제

### ISSUE THREAD

**Issue by Designated-Hitter** [Team-def/recre-frontend#188]

**Comment by ChoiWheatley** [comment]
감정표현 element가 사라지지 않고 게임 중 남아서 마우스 그림 그리는 것을 방해하고 있었습니다.

![Image](https://github.com/Team-def/recre-frontend/assets/18757823/4ccc828a-9d20-47e9-aeea-39f3042cfa9a)
