### ISSUE TITLE
.env로 URL이나 포트번호 관리

### ISSUE THREAD

**Issue by Designated-Hitter** [Team-def/recre-frontend#48]
,env로 URL이나 포트번호를 관리하여 push나 pull 이후 번거롭게 해당 정보를 고쳐야 할 필요 없도록

**Comment by poqop721** [comment]
root 디렉토리에 .env.local 을 생성, 그 안에서 내가 쓸 백서버 api나 프론트엔드 url이나 소켓 서버 api url들을 넣었습니다.
사용할 땐 'process.env.환경변수명' 형식으로 사용하여 바꿔놨습니다.
한가지 주의하실 점은 브라우저에서 .env파일을 통해 환경변수를 사용할 때 'process.env.NEXT_PUBLIC_변수명'으로 이름을 지어야 합니다.

close https://github.com/Team-def/recre-frontend/pull/27
