### ISSUE TITLE
[FE] 플레이어 대기방에서 leave_game 메시지를 받았을때 참가하기 버튼이 다시 활성화되게 해주세요

### ISSUE THREAD

**Issue by ChoiWheatley** [Team-def/recre-frontend#55]
유저가 레디를 눌렀는데 5분이 지나 호스트가 게임을 시작하지 않은 경우 -> timeout이 되어 connection이 끊어지지만 참가하기 버튼이 다시 나타나지 않음

**Comment by DongPark987** [comment]
소켓 서버에서 
게임에 참가중인 클라이언트가 타임아웃으로 인해 대기방에서 종료가 되는 경우
 client.emit('leave_game', { result: true });
위 코드로 "leave_game" 메시지로 통신이 감
@poqop721

**Comment by ChoiWheatley** [comment]
15분 지나면 자동으로 leave하게 되어 이슈 닫습니다.
